# Generated by Django 5.1.2 on 2024-10-15 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('manageBook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='account',
        ),
        migrations.RemoveField(
            model_name='member',
            name='account',
        ),
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='borrowbook',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='borrowbook',
            name='borrow_history_id',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='borrow_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageBook.book'),
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='borrow_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.borrowhistory'),
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='position_in_queue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='queue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manageBook.book'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.cart'),
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='book_returned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
