# Generated by Django 5.1.2 on 2024-10-16 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_staff_account_remove_member_account_and_more'),
        ('manageBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowhistory',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manageBook.book'),
        ),
    ]
