# Generated by Django 5.1.2 on 2024-10-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_borrowhistory_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='create_date',
        ),
    ]
