# Generated by Django 5.1.2 on 2024-10-16 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_cart_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowbook',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RemoveField(
            model_name='borrowbook',
            name='borrow_history',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='book_returned',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='position_in_queue',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='queue_date',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='status',
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='queue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.cart'),
        ),
    ]
