# Generated by Django 5.1.2 on 2024-10-16 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_book_borrowbook_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='history_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.borrowhistory'),
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.bookstatus'),
        ),
    ]
