# Generated by Django 5.1.2 on 2024-10-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_borrowbook_history_id_borrowbook_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowbook',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='borrowbook',
            old_name='history_id',
            new_name='history',
        ),
    ]
