# Generated by Django 5.1.2 on 2024-10-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_book_id_borrowbook_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowhistory',
            name='borrow_date',
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='queue_date',
            field=models.DateField(null=True),
        ),
    ]
