# Generated by Django 5.1.2 on 2024-10-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_borrowhistory_borrow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='borrow_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
