# Generated by Django 5.1.2 on 2024-10-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_borrowbook_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='queue_date',
            field=models.DateTimeField(null=True),
        ),
    ]
