# Generated by Django 5.1.2 on 2024-10-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
