# Generated by Django 5.1.2 on 2024-10-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageBook', '0002_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
